controller:
  - portName: DJControl Inpulse 500 MIDI 1
    vendorID: 0x45e
    productID: 0x285
    mappings:
      - comment: Play left
        type: button
        midiChannel: 1
        midiKey: 7
        button: south
      - comment: Volume left
        type: control
        midiChannel: 1
        midiController: 0
        axis: left-y
