controller:
  - portName: DJControl Inpulse 500 MIDI 1  # name of the MIDI port to read from. You can find it with aseqdump -l
    vendorID: 0x45e   # vendor ID for the virtual gamepad. Default is 0x45e. See https://gist.github.com/nondebug/aec93dff7f0f1969f4cc2291b24a3171
    productID: 0x285  # product ID for the virtual gamepad. Default is 0x285. See https://gist.github.com/nondebug/aec93dff7f0f1969f4cc2291b24a3171
    mappings:
      - comment: Play left # This is optional, but it can increase comprehensibility. Will also be used in debug output.
        type: button       # Either button or axis. A button can be pressed or released, an axis represents a range of values.
        midiChannel: 1     # MIDI channel to listen to
        midiKey: 7         # MIDI note representing the button
        button: west       # Name of the gamepad button this should be mapped to. For valid names, see README.md
      - comment: Filter left
        type: axis
        midiChannel: 1
        midiController: 1 # MIDI controller representing the physical control
        axis: left-x      # Axis on the virtual gamepad this should be mapped to. For valid names, see README.md
        isSigned: true    # Whether the controller axis should range from -1 to 1 or from 0 to 1. Default is false
        deadzone: 0.01    # Number between 0 and 1. In this case, all values between -0.01 and 0.01 will be clamped to 0. Default is 0.0
      - comment: Volume left
        type: axis
        midiChannel: 1
        midiController: 0
        axis: left-y
      - comment: Loop left
        type: encoder
        midiChannel: 1
        midiController: 14
        button: dpad-right        # Clockwise
        buttonNegative: dpad-left # Counter-Clockwise
